// Autogenerated from Pigeon (v10.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum IRInstallationType {
  appStore,
  test,
  debug,
  unknown,
}

enum IRInstallationPlatform {
  appleAppStore,
  appleTestflight,
  googlePlay,
  amazonAppStore,
  huaweiAppGallery,
  oppoAppMarket,
  samsungAppShop,
  vivoAppStore,
  xiaomiAppStore,
  manually,
  unknown,
}

enum IRPlatform {
  ios,
  android,
  macos,
}

class IRInstallationReferer {
  IRInstallationReferer({
    this.type,
    this.installationPlatform,
    this.platform,
    this.packageName,
  });

  IRInstallationType? type;

  IRInstallationPlatform? installationPlatform;

  IRPlatform? platform;

  String? packageName;

  Object encode() {
    return <Object?>[
      type?.index,
      installationPlatform?.index,
      platform?.index,
      packageName,
    ];
  }

  static IRInstallationReferer decode(Object result) {
    result as List<Object?>;
    return IRInstallationReferer(
      type: result[0] != null
          ? IRInstallationType.values[result[0]! as int]
          : null,
      installationPlatform: result[1] != null
          ? IRInstallationPlatform.values[result[1]! as int]
          : null,
      platform: result[2] != null
          ? IRPlatform.values[result[2]! as int]
          : null,
      packageName: result[3] as String?,
    );
  }
}

class _InstallReferrerInternalAPICodec extends StandardMessageCodec {
  const _InstallReferrerInternalAPICodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is IRInstallationReferer) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return IRInstallationReferer.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class InstallReferrerInternalAPI {
  /// Constructor for [InstallReferrerInternalAPI].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  InstallReferrerInternalAPI({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _InstallReferrerInternalAPICodec();

  Future<IRInstallationReferer> detectReferrer() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.InstallReferrerInternalAPI.detectReferrer', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as IRInstallationReferer?)!;
    }
  }
}
