// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Messages.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation IRIRInstallationTypeBox
- (instancetype)initWithValue:(IRIRInstallationType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation IRIRInstallationPlatformBox
- (instancetype)initWithValue:(IRIRInstallationPlatform)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation IRIRPlatformBox
- (instancetype)initWithValue:(IRIRPlatform)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface IRIRInstallationReferer ()
+ (IRIRInstallationReferer *)fromList:(NSArray<id> *)list;
+ (nullable IRIRInstallationReferer *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation IRIRInstallationReferer
+ (instancetype)makeWithType:(nullable IRIRInstallationTypeBox *)type
    installationPlatform:(nullable IRIRInstallationPlatformBox *)installationPlatform
    platform:(nullable IRIRPlatformBox *)platform
    packageName:(nullable NSString *)packageName {
  IRIRInstallationReferer* pigeonResult = [[IRIRInstallationReferer alloc] init];
  pigeonResult.type = type;
  pigeonResult.installationPlatform = installationPlatform;
  pigeonResult.platform = platform;
  pigeonResult.packageName = packageName;
  return pigeonResult;
}
+ (IRIRInstallationReferer *)fromList:(NSArray<id> *)list {
  IRIRInstallationReferer *pigeonResult = [[IRIRInstallationReferer alloc] init];
  pigeonResult.type = GetNullableObjectAtIndex(list, 0);
  pigeonResult.installationPlatform = GetNullableObjectAtIndex(list, 1);
  pigeonResult.platform = GetNullableObjectAtIndex(list, 2);
  pigeonResult.packageName = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable IRIRInstallationReferer *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [IRIRInstallationReferer fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.type ?: [NSNull null],
    self.installationPlatform ?: [NSNull null],
    self.platform ?: [NSNull null],
    self.packageName ?: [NSNull null],
  ];
}
@end

@interface IRMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation IRMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[IRIRInstallationTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[IRIRInstallationPlatformBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[IRIRPlatformBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 132: 
      return [IRIRInstallationReferer fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface IRMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation IRMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[IRIRInstallationTypeBox class]]) {
    IRIRInstallationTypeBox *box = (IRIRInstallationTypeBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[IRIRInstallationPlatformBox class]]) {
    IRIRInstallationPlatformBox *box = (IRIRInstallationPlatformBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[IRIRPlatformBox class]]) {
    IRIRPlatformBox *box = (IRIRPlatformBox *)value;
    [self writeByte:131];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[IRIRInstallationReferer class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface IRMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation IRMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[IRMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[IRMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *IRGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    IRMessagesPigeonCodecReaderWriter *readerWriter = [[IRMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpIRInstallReferrerInternalAPI(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IRInstallReferrerInternalAPI> *api) {
  SetUpIRInstallReferrerInternalAPIWithSuffix(binaryMessenger, api, @"");
}

void SetUpIRInstallReferrerInternalAPIWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IRInstallReferrerInternalAPI> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.install_referrer.InstallReferrerInternalAPI.detectReferrer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:IRGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(detectReferrerWithCompletion:)], @"IRInstallReferrerInternalAPI api (%@) doesn't respond to @selector(detectReferrerWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api detectReferrerWithCompletion:^(IRIRInstallationReferer *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
