// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, IRIRInstallationType) {
  IRIRInstallationTypeAppStore = 0,
  IRIRInstallationTypeTest = 1,
  IRIRInstallationTypeDebug = 2,
  IRIRInstallationTypeUnknown = 3,
};

/// Wrapper for IRIRInstallationType to allow for nullability.
@interface IRIRInstallationTypeBox : NSObject
@property(nonatomic, assign) IRIRInstallationType value;
- (instancetype)initWithValue:(IRIRInstallationType)value;
@end

typedef NS_ENUM(NSUInteger, IRIRInstallationPlatform) {
  IRIRInstallationPlatformAppleAppStore = 0,
  IRIRInstallationPlatformAppleTestflight = 1,
  IRIRInstallationPlatformGooglePlay = 2,
  IRIRInstallationPlatformAmazonAppStore = 3,
  IRIRInstallationPlatformHuaweiAppGallery = 4,
  IRIRInstallationPlatformOppoAppMarket = 5,
  IRIRInstallationPlatformSamsungAppShop = 6,
  IRIRInstallationPlatformVivoAppStore = 7,
  IRIRInstallationPlatformXiaomiAppStore = 8,
  IRIRInstallationPlatformManually = 9,
  IRIRInstallationPlatformUnknown = 10,
};

/// Wrapper for IRIRInstallationPlatform to allow for nullability.
@interface IRIRInstallationPlatformBox : NSObject
@property(nonatomic, assign) IRIRInstallationPlatform value;
- (instancetype)initWithValue:(IRIRInstallationPlatform)value;
@end

typedef NS_ENUM(NSUInteger, IRIRPlatform) {
  IRIRPlatformIos = 0,
  IRIRPlatformAndroid = 1,
  IRIRPlatformMacos = 2,
};

/// Wrapper for IRIRPlatform to allow for nullability.
@interface IRIRPlatformBox : NSObject
@property(nonatomic, assign) IRIRPlatform value;
- (instancetype)initWithValue:(IRIRPlatform)value;
@end

@class IRIRInstallationReferer;

@interface IRIRInstallationReferer : NSObject
+ (instancetype)makeWithType:(nullable IRIRInstallationTypeBox *)type
    installationPlatform:(nullable IRIRInstallationPlatformBox *)installationPlatform
    platform:(nullable IRIRPlatformBox *)platform
    packageName:(nullable NSString *)packageName;
@property(nonatomic, strong, nullable) IRIRInstallationTypeBox * type;
@property(nonatomic, strong, nullable) IRIRInstallationPlatformBox * installationPlatform;
@property(nonatomic, strong, nullable) IRIRPlatformBox * platform;
@property(nonatomic, copy, nullable) NSString * packageName;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *IRGetMessagesCodec(void);

@protocol IRInstallReferrerInternalAPI
- (void)detectReferrerWithCompletion:(void (^)(IRIRInstallationReferer *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpIRInstallReferrerInternalAPI(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IRInstallReferrerInternalAPI> *_Nullable api);

extern void SetUpIRInstallReferrerInternalAPIWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IRInstallReferrerInternalAPI> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
